Repository ropensci/mapmetadata, pull requests merged in 2024-11, with the labels that each got.

#142 version 2.0.0
  .github/workflows/update-citation-cff.yaml
  CITATION.cff
  README.md
  codemeta.json
  inst/CITATION
Labels: documentation

#148 add bug fix location + add badge
  DESCRIPTION
  README.md
Labels: documentation

#150 Indicate internal functions
  R/collect_inputs.R
  R/compare.R
  R/data-package_data.R
  R/data_manipulation.R
  R/plotting.R
  R/user_interactions.R
Labels: enhancement, ready for review

#153 Update pull_request_template.md
  .github/pull_request_template.md
Labels: internal

#156 Add examples to functions
  R/browse_metadata.R
  R/map_metadata.R
  R/map_metadata_compare.R
  R/map_metadata_convert.R
  codemeta.json
  inst/outputs/LOG_NationalCommunityChildHealthDatabase(NCCHD)_CHILD_2024-11-27-14-19-55.csv
  inst/outputs/LOG_NationalCommunityChildHealthDatabase(NCCHD)_CHILD_2024-11-27-14-23-52.csv
  inst/outputs/OUTPUT_NationalCommunityChildHealthDatabase(NCCHD)_CHILD_2024-11-27-14-19-55.csv
  inst/outputs/OUTPUT_NationalCommunityChildHealthDatabase(NCCHD)_CHILD_2024-11-27-14-23-52.csv
  inst/outputs/PLOT_NationalCommunityChildHealthDatabase(NCCHD)_CHILD_2024-11-27-14-19-55.png
  inst/outputs/PLOT_NationalCommunityChildHealthDatabase(NCCHD)_CHILD_2024-11-27-14-23-52.png
  man/browse_metadata.Rd
  man/map_metadata.Rd
  man/map_metadata_compare.Rd
  man/map_metadata_convert.Rd
Labels: documentation
