Repository ropensci/mapmetadata, pull requests merged in 2024-07, with the labels that each got.

#100 Fix bug with header of demo list file
  R/data-domain_list.R
  R/domain_mapping.R
  data-raw/domain_list_demo.csv
  data/domain_list.rda
  man/domain_list.Rd
Labels: documentation

#104 Re-work the csv output logs & validate user inputs
  DESCRIPTION
  NAMESPACE
  R/compare_csv_outputs.R
  R/compare_sessions.R
  R/domain_mapping.R
  R/user_categorisation.R
  README.md
  man/compare_csv_outputs.Rd
  man/compare_sessions.Rd
  man/user_categorisation.Rd
Labels: documentation, enhancement, bug-fix

#105 Add in table dependencies (quicker for user and more valid)
  R/compare_sessions.R
  R/domain_mapping.R
  README.md
  man/compare_sessions.Rd
  man/domain_mapping.Rd
Labels: documentation, enhancement

#111 Copy previous categorisations from multiple tables not just one
  DESCRIPTION
  NAMESPACE
  R/domain_mapping.R
  README.md
  man/domain_mapping.Rd
Labels: documentation, bug-fix

#112 Add hexagone Package logo
  DESCRIPTION
  README.md
  _pkgdown.yml
  man/figures/logo.png
  pkgdown/favicon/apple-touch-icon-120x120.png
  pkgdown/favicon/apple-touch-icon-152x152.png
  pkgdown/favicon/apple-touch-icon-180x180.png
  pkgdown/favicon/apple-touch-icon-60x60.png
  pkgdown/favicon/apple-touch-icon-76x76.png
  pkgdown/favicon/apple-touch-icon.png
  pkgdown/favicon/favicon-16x16.png
  pkgdown/favicon/favicon-32x32.png
  pkgdown/favicon/favicon.ico
Labels: documentation, enhancement

#113 Updating to main
  DESCRIPTION
  README.md
  _pkgdown.yml
  man/figures/logo.png
  pkgdown/favicon/apple-touch-icon-120x120.png
  pkgdown/favicon/apple-touch-icon-152x152.png
  pkgdown/favicon/apple-touch-icon-180x180.png
  pkgdown/favicon/apple-touch-icon-60x60.png
  pkgdown/favicon/apple-touch-icon-76x76.png
  pkgdown/favicon/apple-touch-icon.png
  pkgdown/favicon/favicon-16x16.png
  pkgdown/favicon/favicon-32x32.png
  pkgdown/favicon/favicon.ico
Labels: documentation

#114 Add function
  NAMESPACE
  R/convert_output.R
  README.md
  man/convert_output.Rd
Labels: documentation, enhancement

#115 Update version number in files, for next release
  CITATION.cff
  DESCRIPTION
  README.md
  inst/CITATION
Labels: documentation, internal
